

#ifndef INCLUDE_MCAL_DIO_DIO_CFG_H_
#define INCLUDE_MCAL_DIO_DIO_CFG_H_

#define PIN_INPUT  0
#define PIN_OUTPUT 1

#define PA0_INITIAL_DIRECTION	 PIN_INPUT // FOR ADC0
#define PA1_INITIAL_DIRECTION	 PIN_INPUT // FOR ADC1

#define PA2_INITIAL_DIRECTION	 PIN_OUTPUT //RED LEDS
#define PA3_INITIAL_DIRECTION	 PIN_OUTPUT //GREEN LEDS
#define PA4_INITIAL_DIRECTION	 PIN_OUTPUT //YELLOW LEDS

#define PA5_INITIAL_DIRECTION	 PIN_OUTPUT //LCD EN PIN
#define PA6_INITIAL_DIRECTION	 PIN_OUTPUT //LCD RW PIN
#define PA7_INITIAL_DIRECTION	 PIN_OUTPUT //LCD RS PIN


//PORTB
#define PB0_INITIAL_DIRECTION	 PIN_OUTPUT  //KeyPad ROW0
#define PB1_INITIAL_DIRECTION	 PIN_INPUT   //KEYPAD COL0
#define PB2_INITIAL_DIRECTION	 PIN_INPUT   //KEYPAD COL1  -->


#define PB3_INITIAL_DIRECTION	 PIN_OUTPUT //MOTOR_BLUE_PIN
#define PB4_INITIAL_DIRECTION	 PIN_OUTPUT //MOTOR_PINK_PIN
#define PB5_INITIAL_DIRECTION	 PIN_OUTPUT //MOTOR_YELLOW_PIN
#define PB6_INITIAL_DIRECTION	 PIN_OUTPUT //MOTOR_ORANGE_PIN


#define PB7_INITIAL_DIRECTION	 PIN_INPUT



//PORTC
#define PC0_INITIAL_DIRECTION	 PIN_OUTPUT   //FOR LCD
#define PC1_INITIAL_DIRECTION	 PIN_OUTPUT
#define PC2_INITIAL_DIRECTION	 PIN_OUTPUT
#define PC3_INITIAL_DIRECTION	 PIN_OUTPUT
#define PC4_INITIAL_DIRECTION	 PIN_OUTPUT
#define PC5_INITIAL_DIRECTION	 PIN_OUTPUT
#define PC6_INITIAL_DIRECTION	 PIN_OUTPUT
#define PC7_INITIAL_DIRECTION	 PIN_OUTPUT





//PORTD
#define PD0_INITIAL_DIRECTION	 PIN_INPUT  //UART RX
#define PD1_INITIAL_DIRECTION	 PIN_OUTPUT //UART TX

#define PD2_INITIAL_DIRECTION	 PIN_INPUT  // INT 0
#define PD3_INITIAL_DIRECTION	 PIN_INPUT  // INT 1

#define PD4_INITIAL_DIRECTION	 PIN_OUTPUT // LOCK
#define PD5_INITIAL_DIRECTION	 PIN_INPUT 

#define PD6_INITIAL_DIRECTION	 PIN_OUTPUT //BUZZER
#define PD7_INITIAL_DIRECTION	 PIN_OUTPUT //DC MOTOR


/************************************************************/

#define PIN_HIGH 1
#define PIN_LOW  0

#define PIN_FLOATING 0
#define PIN_PULLUP   1


//PORTA
#define PA0_INITIAL_VALUE	 PIN_PULLUP //ADC
#define PA1_INITIAL_VALUE	 PIN_PULLUP


#define PA2_INITIAL_VALUE	 PIN_LOW //RED_LEDS
#define PA3_INITIAL_VALUE	 PIN_LOW
#define PA4_INITIAL_VALUE	 PIN_LOW

#define PA5_INITIAL_VALUE	 PIN_LOW //LCD_CONTROL_PINS
#define PA6_INITIAL_VALUE	 PIN_LOW
#define PA7_INITIAL_VALUE	 PIN_LOW




//PORTB
#define PB0_INITIAL_VALUE	 PIN_LOW //KEYPAD
#define PB1_INITIAL_VALUE	 PIN_FLOATING
#define PB2_INITIAL_VALUE	 PIN_FLOATING

#define PB3_INITIAL_VALUE	 PIN_LOW  //STEPUP_MOTOR_PINS
#define PB4_INITIAL_VALUE	 PIN_LOW
#define PB5_INITIAL_VALUE	 PIN_LOW
#define PB6_INITIAL_VALUE	 PIN_LOW

#define PB7_INITIAL_VALUE	 PIN_LOW




//PORTC
#define PC0_INITIAL_VALUE	 PIN_LOW  //FOR LCD
#define PC1_INITIAL_VALUE	 PIN_LOW
#define PC2_INITIAL_VALUE	 PIN_LOW
#define PC3_INITIAL_VALUE	 PIN_LOW
#define PC4_INITIAL_VALUE	 PIN_LOW
#define PC5_INITIAL_VALUE	 PIN_LOW
#define PC6_INITIAL_VALUE	 PIN_LOW
#define PC7_INITIAL_VALUE	 PIN_LOW




//PORTD
#define PD0_INITIAL_VALUE	 PIN_FLOATING //UART
#define PD1_INITIAL_VALUE	 PIN_LOW

#define PD2_INITIAL_VALUE	 PIN_PULLUP  //Falling edge
#define PD3_INITIAL_VALUE	 PIN_PULLUP

#define PD4_INITIAL_VALUE	 PIN_LOW //LOCKED
#define PD5_INITIAL_VALUE	 PIN_FLOATING

#define PD6_INITIAL_VALUE	 PIN_LOW  //BUZZER

#define PD7_INITIAL_VALUE	 PIN_LOW       //DC MOTOR



#endif /* INCLUDE_MCAL_DIO_DIO_CFG_H_ */
