///*****************************************************************************/
//
///* File Defination :
// *
// * File 		: STPR_program.c
// *
// * Created on	: Sep 30, 2023
// *
// */
///*****************************************************************************/
//
//
//
//Basic Includes
#include "../Include/LIB/STD_TYPES.h"
#include "../Include/LIB/BIT_MATH.h"
#include <avr/delay.h>


//MCAL Includes
#include "../Include/MCAL/DIO/DIO_Interface.h"

//STEP motor in
#include "../Include/HAL/STEP_UP_MOTOR/STEPMOTOR_Interface.h"
#include "../Include/HAL/STEP_UP_MOTOR/STEPMOTOR_Private.h"
#include "../Include/HAL/STEP_UP_MOTOR/STEPMOTOR_Cfg.h"


//HAL includes
#include "../Include/HAL/LEDS/LEDS_Interface.h"
#include "../Include/HAL/LEDS/LEDS_CFG.h"
#include "../Include/HAL/LCD/LCD_interface.h"

/*CLOCKWISE*/
void STEPPER_Rotate_CW_Full_Step(void)
{
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_SET);
	_delay_ms(2);
}







/*COUNTER-CLOCKWISE*/
void STEPPER_Rotate_ACW_Full_Step(void)
{
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_SET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);

}

void STEPPER_Rotate_CW_Half_Step(void)
{

	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_SET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);

	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_SET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_SET);
	_delay_ms(2);


}
void STEPPER_Rotate_ACW_Half_Step(void)
{

	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_SET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_SET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);

	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_RESET);
	_delay_ms(2);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_BLUE_PIN,DIO_SET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_PINK_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_YELLOW_PIN,DIO_RESET);
	MDIO_voidSetPinValue(STEP_UP_MOTOR_PORT,COIL_ORANGE_PIN,DIO_SET);
	_delay_ms(2);

}


void STEPPER_Set_Angle(u32 angle , u8 direction)
{
	u32 steps = (angle * 2048) / 360;
	u32 loops = steps / 4;
	u32 i;
	if( direction== CW)
	{
		for(i= 0 ; i < loops ; i++)
		{
			STEPPER_Rotate_CW_Full_Step();
		}
	}
	else
	{
		for(i=0 ; i < loops ; i++)
		{
			STEPPER_Rotate_ACW_Full_Step();
		}
	}
}
